mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    #path('polls/', include('polls.urls')),
    path('punkt/', include('punkt.urls')),
    path('admin/', admin.site.urls),
    
]

mysite/punkt/urls.py
from django.urls import path


from . import views

app_name = 'punkt'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:punkt_id>/', views.detail, name = 'detail'),
]

mysite/punkt/models.py
from django.db import models 
#from mapbox_location_field.models import LocationField
#import punkt.mqtt as mqtt
#import datetime
#from django.utils import timezone

# Create your models here.

class Punkt(models.Model):
    punkt_text = models.CharField(max_length=200)
    punkt_oppdatert = models.DateTimeField('date updated')
    def __str__(self):
        return self.punkt_text

    

class Measurement(models.Model):
    punkt = models.ForeignKey(Punkt, on_delete=models.CASCADE)
    measurement_text = models.CharField(max_length=200)
    #measure = models.IntegerField(default=0)
    def __str__(self):
        return self.measurement_text



    

    
    
    

mysite/punkt/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.http import Http404
#from django.template import loader

from .models import Measurement, Punkt


def index(request):
    punkt_liste = Punkt.objects.all()
    measurement_liste = Measurement.objects.all()
    #template = loader.get_template('punkt/index.html')
    context = {
        'punkt_liste': punkt_liste, 
        'measurement_liste' : measurement_liste,
    }
    #output = ', '.join([p.punkt_text for p in punkt_liste])
    #return HttpResponse(template.render(context, request))
    return render(request, 'punkt/index.html', context)



def detail(request, punkt_id):
    #try:
     #   punkt = Punkt.objects.get(pk=punkt_id)
    #except Punkt.DoesNotExist:
     #   raise Http404("Punkt finnes ikke")
    #return HttpResponse("Du ser paa %s." % punkt_id)
    punkt = get_object_or_404(Punkt, pk = punkt_id)
    return render(request, 'punkt/detail.html', {'punkt':punkt})



mysite/punkt/templates/punkt/detail.html

<h1>{{ punkt.punkt_text }}</h1>
<ul>
{% for measurement in punkt.measurement_set.all %}
    <li>{{ measurement.measurement_text }}</li>
{% endfor %}
</ul>

mysite/punkt/templates/punkt/index.html
{% load static %}

<link rel= "stylesheet" type="text/css" href = "{% static 'punkt/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">



<head>
<!--Installasjon av Mapbox GL JS -->
<script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />

<!--Overskrift-->
<h1> Snowpilot </h1>

</head>

<body>
    <div id='map' style='width: 100%; height: 100%;'></div>
    
    <script>
    //----Implementasjon av kartet---- 
    mapboxgl.accessToken = 'pk.eyJ1IjoibWFyZW5zdGgiLCJhIjoiY2wwYW9peWZmMDBxZDNkb3Z5eGZ5NWR6MyJ9.Z_GIlVGbyEHe9DxGWHBnUQ';
    var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [10.42, 63.42],
    zoom: 12.5
    });
    
    //funksjon for å konvertere HTML-element til streng
    function convertToPlain(html){

        // Create a new div element
        var tempDivElement = document.createElement("div");
    
        // Set the HTML content with the given value
        tempDivElement.innerHTML = html;
    
        // Retrieve the text property of the element 
        return tempDivElement.textContent || tempDivElement.innerText || "";
    }

    //----Linken til Github-siden som en HTML-streng----
    var htmlString = "<div><p> {{measurement_liste.0.measurement_text}}</p></div>";
    
    //----Data til punktmålingene----
    var geoJson ={  
            "features": [
            {
                "type": "Feature",
                "properties": {
                    //title sier hvor systemet er
                    "title": "Extra Elgeseter",
                    //link hyperlinker til Github-siden
                    "description": "",
                    "link": '<a href = "'+ convertToPlain("<div><p> {{measurement_liste.0.measurement_text}}</p></div>") +'"> Maaling </a>'
                
                },
                "geometry": {
                    "coordinates": [ 10.396258819163721,63.418775786010265],
                    "type": "Point"
                }
            },
            //----Resten av punktene er for demostrasjon, Dummy punkter
            //----Har ikke tilknyttet en link til seg
            {
                "type": "Feature",
                "properties": {
                    "title": "Ohma Electra",
                    //description sier noe om føret siden det ikke har en tilknyttet målesystem
                    "description": "Snow 6 cm"
                    
                },
                "geometry": {
                    "coordinates": [ 10.401497705501342, 63.41861989991297 ],
                    "type": "Point"
                }
                },
            {
                "type": "Feature",
                "properties": {
                    "title": "Skansen",
                    "description": "Snow: 5 cm"
                    
                },
                "geometry": {
                    "coordinates": [ 10.377204269865686, 63.4311193541111 ],
                    "type": "Point"
                }
                },
            {
                "type": "Feature",
                "properties": {
                    "title": "Weidemanns vei",
                    "description": "Snow: 8.5 cm"
                    
                },
                "geometry": {
                    "coordinates": [ 10.415364588859784, 63.43127798919796],
                    "type": "Point"
                }
                },
            {
                "type": "Feature",
                "properties": {
                    "title": "Gamle bybro",
                    "description": "Snow: 9 cm"
                    
                },
                "geometry": {
                    "coordinates": [ 10.401540652185586,63.428292640617286],
                    "type": "Point"
                }
                }
            ],
            "type": "FeatureCollection" 
    }
    
        
    
    map.on('load', () => {
                
        //----Lager popup-objekter----
        const popup_1 = new mapboxgl.Popup({ offset: [0, -15] })
               .setHTML(
               `<h3>${geoJson.features[0].properties.title}</h3><p>${geoJson.features[0].properties.link}</p>`
               
            );

        const popup_2 = new mapboxgl.Popup({ offset: [0, -15] })
            
                .setHTML(
               `<h3>${geoJson.features[1].properties.title}</h3><p>${geoJson.features[1].properties.description}</p>`
               
            );
        const popup_3 = new mapboxgl.Popup({ offset: [0, -15] })
                .setHTML(
                `<h3>${geoJson.features[2].properties.title}</h3><p>${geoJson.features[2].properties.description}</p>`
        
            );
        const popup_4 = new mapboxgl.Popup({ offset: [0, -15] })
                .setHTML(
                `<h3>${geoJson.features[3].properties.title}</h3><p>${geoJson.features[3].properties.description}</p>`
            
            );
        const popup_5 = new mapboxgl.Popup({ offset: [0, -15] })
                .setHTML(
                `<h3>${geoJson.features[4].properties.title}</h3><p>${geoJson.features[4].properties.description}</p>`
            );
        

        //----Lager marker-objekter----
        const marker_1 = new mapboxgl.Marker().setLngLat(geoJson.features[0].geometry.coordinates).setPopup(popup_1).addTo(map);
        const marker_2 = new mapboxgl.Marker().setLngLat(geoJson.features[1].geometry.coordinates).setPopup(popup_2).addTo(map);
        const marker_3 = new mapboxgl.Marker().setLngLat(geoJson.features[2].geometry.coordinates).setPopup(popup_3).addTo(map);
        const marker_4 = new mapboxgl.Marker().setLngLat(geoJson.features[3].geometry.coordinates).setPopup(popup_4).addTo(map);
        const marker_5 = new mapboxgl.Marker().setLngLat(geoJson.features[4].geometry.coordinates).setPopup(popup_5).addTo(map);
    } 
        
    );
          
    </script>
</body>